---
  - name: add TreasureData repo
    template: src=templates/td.repo dest=/etc/yum.repos.d/td.repo owner=root group=root mode=0644
    register: tdrepo

  - name: install td GPG key
    rpm_key: key=http://packages.treasuredata.com/GPG-KEY-td-agent state=present

  - name: install fluentd 
    yum: "pkg=td-agent state=installed"

#  - name: install rubygems (for fluentd plugins) - not needed?
#    yum: "pkg=rubygems state=installed"

  - name: install fluentd plugins
    command: td-agent-gem install fluent-plugin-elasticsearch

  - name: add td-agent config file
    template: src=templates/td-agent.conf dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644

  - name: enable services on boot
    service: name=td-agent enabled=yes state=started
