---
# defaults for ansible-role-logstash
#

configure_logstash: True

add_logstash_repofile : True

programs_to_install:
  - logstash
  - httpd
  - mod_ssl
  - mod_authz_ldap
  - curl
el7programs_to_install:
  - logstash
  - httpd
  - mod_ssl
  - curl
  - mod_ldap
programs_on_boot:
  - logstash
  - httpd

logstash_prod_example: True

logstash_version: "1.5"
