---
# Can't use template validate option because apachectl must be pointed to httpd.conf..
#

  - name: copy in httpd config file
    template: src=templates/httpd-logstash.conf.j2 dest=/etc/httpd/conf.d/logstash.conf owner=apache group=apache mode=0640 backup=yes
    register: httpdconfig
    when: ansible_os_family == "RedHat"

  - name: copy in ssl config file if kibana4_https is set to on
    template: src=templates/httpd-01ssl.conf.j2 dest=/etc/httpd/conf.d/01ssl.conf owner=apache group=apache mode=0640 backup=yes
    register: httpdconfig2
    when: ansible_os_family == "RedHat" and kibana4_https == "on"

  - name: write some garbage into ssl.conf - so it is not overwritten on httpd upgrades
    copy: content="# this file is unused" dest=/etc/httpd/conf.d/ssl.conf backup=yes
    when: ansible_os_family == "RedHat"

  - name: install software from logstash repo
    # If we set state=latest this takes a long time to run.
    yum: "pkg={{item}} state=installed"
    with_items: programs_to_install
    when: ansible_distribution_major_version == "6"

  - name: install software from logstash repo EL7
    # If we set state=latest this takes a long time to run.
    yum: "pkg={{item}} state=installed"
    with_items: el7programs_to_install
    when: ansible_distribution_major_version == "7"

  - name: enable services on boot
    service: name={{item}} enabled=yes
    with_items: programs_on_boot

  - name: start httpd
    service: name=httpd state=started

  - name: restart httpd if httpdconfig or certs has changed
    service: name=httpd state=restarted
    when: httpdconfig.changed or httpdconfig2.changed
